sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: john123!
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tGUMzFwqjwhM5kE6sm7
    access-key-secret: gsK842Z60IL0LJ0wHPTtuzsVJWBNv3
    bucket-name: dqyweb-sky
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wxc68925b757e53cdd
    secret: 32752df5f6564a051572af204de90336
